apiVersion: v1
kind: ConfigMap
metadata:
  name: videotube-config
  namespace: videotube
data:
  PORT: "8000"
  NODE_ENV: "production"
  CORS_ORIGIN: "http://localhost,http://localhost:80,http://localhost:5173"
  REDIS_HOST: "videotube-redis-service"
  REDIS_PORT: "6379"
  STORAGE_PROVIDER: "s3"
  AWS_REGION: "us-east-1"
